//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

/** Apple Test Flight Groups Response Type */
public class AppleTestFlightGroupsResponse: APIModel {

    /** apple id of the group. */
    public var appleId: Double?

    /** id of the group. */
    public var id: String?

    /** name of the group. */
    public var name: String?

    /** provider id of the group. */
    public var providerId: Double?

    public init(appleId: Double? = nil, id: String? = nil, name: String? = nil, providerId: Double? = nil) {
        self.appleId = appleId
        self.id = id
        self.name = name
        self.providerId = providerId
    }

    private enum CodingKeys: String, CodingKey {
        case appleId
        case id
        case name
        case providerId
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        appleId = try container.decodeIfPresent(.appleId)
        id = try container.decodeIfPresent(.id)
        name = try container.decodeIfPresent(.name)
        providerId = try container.decodeIfPresent(.providerId)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)

        try container.encodeIfPresent(appleId, forKey: .appleId)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(providerId, forKey: .providerId)
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? AppleTestFlightGroupsResponse else { return false }
      guard self.appleId == object.appleId else { return false }
      guard self.id == object.id else { return false }
      guard self.name == object.name else { return false }
      guard self.providerId == object.providerId else { return false }
      return true
    }

    public static func == (lhs: AppleTestFlightGroupsResponse, rhs: AppleTestFlightGroupsResponse) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
