//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

/** Apple secret details */
public class AppleSecretDetails: APIModel {

    /** 6 digit auth code */
    public var authCode: String?

    /** password to connect to apple store. */
    public var password: String?

    /** username to connect to apple store. */
    public var username: String?

    public init(authCode: String? = nil, password: String? = nil, username: String? = nil) {
        self.authCode = authCode
        self.password = password
        self.username = username
    }

    private enum CodingKeys: String, CodingKey {
        case authCode
        case password
        case username
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        authCode = try container.decodeIfPresent(.authCode)
        password = try container.decodeIfPresent(.password)
        username = try container.decodeIfPresent(.username)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)

        try container.encodeIfPresent(authCode, forKey: .authCode)
        try container.encodeIfPresent(password, forKey: .password)
        try container.encodeIfPresent(username, forKey: .username)
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? AppleSecretDetails else { return false }
      guard self.authCode == object.authCode else { return false }
      guard self.password == object.password else { return false }
      guard self.username == object.username else { return false }
      return true
    }

    public static func == (lhs: AppleSecretDetails, rhs: AppleSecretDetails) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
