//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

/** List of device properties. */
public class AudienceDevicePropertiesListResult: APIModel {

    /** List of device properties. */
    public enum Values: String, Codable {
        case string = "string"
        case number = "number"
        case boolean = "boolean"
        case dateTime = "date_time"

        public static let cases: [Values] = [
          .string,
          .number,
          .boolean,
          .dateTime,
        ]
    }

    /** List of device properties. */
    public var values: [String: Values]

    public init(values: [String: Values]) {
        self.values = values
    }

    private enum CodingKeys: String, CodingKey {
        case values
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        values = try container.decode(.values)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)

        try container.encode(values, forKey: .values)
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? AudienceDevicePropertiesListResult else { return false }
      guard self.values == object.values else { return false }
      return true
    }

    public static func == (lhs: AudienceDevicePropertiesListResult, rhs: AudienceDevicePropertiesListResult) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
