//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

/** Audience definition. */
public class AudienceBlobResult: APIModel {

    /** Location of the audience blob. */
    public var url: String?

    public init(url: String? = nil) {
        self.url = url
    }

    private enum CodingKeys: String, CodingKey {
        case url
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        url = try container.decodeIfPresent(.url)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)

        try container.encodeIfPresent(url, forKey: .url)
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? AudienceBlobResult else { return false }
      guard self.url == object.url else { return false }
      return true
    }

    public static func == (lhs: AudienceBlobResult, rhs: AudienceBlobResult) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
