//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

/** A list of queues configured in build definitions */
public typealias BuildAgentQueuesResponse = [BuildAgentQueuesResponse]
