//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class CreateStoreSecretResponse: APIModel {

    /** the secret id for store secret */
    public var secretId: String?

    public init(secretId: String? = nil) {
        self.secretId = secretId
    }

    private enum CodingKeys: String, CodingKey {
        case secretId = "secret_id"
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        secretId = try container.decodeIfPresent(.secretId)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)

        try container.encodeIfPresent(secretId, forKey: .secretId)
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? CreateStoreSecretResponse else { return false }
      guard self.secretId == object.secretId else { return false }
      return true
    }

    public static func == (lhs: CreateStoreSecretResponse, rhs: CreateStoreSecretResponse) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
