//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class CustomProperty: APIModel {

    public var type: String

    public var name: String

    public init(type: String, name: String) {
        self.type = type
        self.name = name
    }

    private enum CodingKeys: String, CodingKey {
        case type
        case name
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        type = try container.decode(.type)
        name = try container.decode(.name)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)

        try container.encode(type, forKey: .type)
        try container.encode(name, forKey: .name)
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? CustomProperty else { return false }
      guard self.type == object.type else { return false }
      guard self.name == object.name else { return false }
      return true
    }

    public static func == (lhs: CustomProperty, rhs: CustomProperty) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
