//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class DistributionStore: APIModel {

    /** type of the distribution store currently stores type can be intune, googleplay or windows. */
    public enum `Type`: String, Codable {
        case intune = "intune"
        case googleplay = "googleplay"
        case apple = "apple"
        case none = "none"

        public static let cases: [`Type`] = [
          .intune,
          .googleplay,
          .apple,
          .none,
        ]
    }

    /** ID identifying a unique distribution store. */
    public var id: String

    /** A name identifying a unique distribution store. */
    public var name: String?

    /** publishing status of the release in the store. */
    public var publishingStatus: String?

    /** type of the distribution store currently stores type can be intune, googleplay or windows. */
    public var type: `Type`?

    public init(id: String, name: String? = nil, publishingStatus: String? = nil, type: `Type`? = nil) {
        self.id = id
        self.name = name
        self.publishingStatus = publishingStatus
        self.type = type
    }

    private enum CodingKeys: String, CodingKey {
        case id
        case name
        case publishingStatus = "publishing_status"
        case type
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        id = try container.decode(.id)
        name = try container.decodeIfPresent(.name)
        publishingStatus = try container.decodeIfPresent(.publishingStatus)
        type = try container.decodeIfPresent(.type)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)

        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(publishingStatus, forKey: .publishingStatus)
        try container.encodeIfPresent(type, forKey: .type)
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? DistributionStore else { return false }
      guard self.id == object.id else { return false }
      guard self.name == object.name else { return false }
      guard self.publishingStatus == object.publishingStatus else { return false }
      guard self.type == object.type else { return false }
      return true
    }

    public static func == (lhs: DistributionStore, rhs: DistributionStore) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
