//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class ErrorGroupModels: APIModel {

    public var errorCount: Int?

    public var models: [Models]?

    public init(errorCount: Int? = nil, models: [Models]? = nil) {
        self.errorCount = errorCount
        self.models = models
    }

    private enum CodingKeys: String, CodingKey {
        case errorCount
        case models
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        errorCount = try container.decodeIfPresent(.errorCount)
        models = try container.decodeArrayIfPresent(.models)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)

        try container.encodeIfPresent(errorCount, forKey: .errorCount)
        try container.encodeIfPresent(models, forKey: .models)
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? ErrorGroupModels else { return false }
      guard self.errorCount == object.errorCount else { return false }
      guard self.models == object.models else { return false }
      return true
    }

    public static func == (lhs: ErrorGroupModels, rhs: ErrorGroupModels) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
