//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

/** An event property value with counts. */
public class EventPropertyValue: APIModel {

    /** The count of the the event property value. */
    public var count: Int?

    /** The event property value name. */
    public var name: String?

    /** The count of previous time range of the event property value. */
    public var previousCount: Int?

    public init(count: Int? = nil, name: String? = nil, previousCount: Int? = nil) {
        self.count = count
        self.name = name
        self.previousCount = previousCount
    }

    private enum CodingKeys: String, CodingKey {
        case count
        case name
        case previousCount = "previous_count"
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        count = try container.decodeIfPresent(.count)
        name = try container.decodeIfPresent(.name)
        previousCount = try container.decodeIfPresent(.previousCount)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)

        try container.encodeIfPresent(count, forKey: .count)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(previousCount, forKey: .previousCount)
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? EventPropertyValue else { return false }
      guard self.count == object.count else { return false }
      guard self.name == object.name else { return false }
      guard self.previousCount == object.previousCount else { return false }
      return true
    }

    public static func == (lhs: EventPropertyValue, rhs: EventPropertyValue) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
