//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class InternalUserSignupResponse: APIModel {

    /** The current status of the user record after signup */
    public enum Status: String, Codable {
        case complete = "Complete"
        case needsVerification = "NeedsVerification"

        public static let cases: [Status] = [
          .complete,
          .needsVerification,
        ]
    }

    /** The unique id (UUID) of the user */
    public var id: ID

    /** The full name of the user. Might for example be first and last name */
    public var displayName: String

    /** The email address of the user */
    public var email: String

    /** The unique name that is used to identify the user. */
    public var name: String

    /** The name of the external auth provider */
    public var externalProvider: String?

    /** The user ID given by the external provider */
    public var externalUserId: String?

    /** The current status of the user record after signup */
    public var status: Status?

    public init(id: ID, displayName: String, email: String, name: String, externalProvider: String? = nil, externalUserId: String? = nil, status: Status? = nil) {
        self.id = id
        self.displayName = displayName
        self.email = email
        self.name = name
        self.externalProvider = externalProvider
        self.externalUserId = externalUserId
        self.status = status
    }

    private enum CodingKeys: String, CodingKey {
        case id
        case displayName = "display_name"
        case email
        case name
        case externalProvider = "external_provider"
        case externalUserId = "external_user_id"
        case status
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        id = try container.decode(.id)
        displayName = try container.decode(.displayName)
        email = try container.decode(.email)
        name = try container.decode(.name)
        externalProvider = try container.decodeIfPresent(.externalProvider)
        externalUserId = try container.decodeIfPresent(.externalUserId)
        status = try container.decodeIfPresent(.status)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)

        try container.encode(id, forKey: .id)
        try container.encode(displayName, forKey: .displayName)
        try container.encode(email, forKey: .email)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(externalProvider, forKey: .externalProvider)
        try container.encodeIfPresent(externalUserId, forKey: .externalUserId)
        try container.encodeIfPresent(status, forKey: .status)
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? InternalUserSignupResponse else { return false }
      guard self.id == object.id else { return false }
      guard self.displayName == object.displayName else { return false }
      guard self.email == object.email else { return false }
      guard self.name == object.name else { return false }
      guard self.externalProvider == object.externalProvider else { return false }
      guard self.externalUserId == object.externalUserId else { return false }
      guard self.status == object.status else { return false }
      return true
    }

    public static func == (lhs: InternalUserSignupResponse, rhs: InternalUserSignupResponse) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
