//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class IntuneGroup: APIModel {

    /** the display name of the group */
    public var displayName: String?

    /** the id of the Group */
    public var id: String?

    /** species if it is a security group */
    public var securityEnabled: Bool?

    public init(displayName: String? = nil, id: String? = nil, securityEnabled: Bool? = nil) {
        self.displayName = displayName
        self.id = id
        self.securityEnabled = securityEnabled
    }

    private enum CodingKeys: String, CodingKey {
        case displayName
        case id
        case securityEnabled
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        displayName = try container.decodeIfPresent(.displayName)
        id = try container.decodeIfPresent(.id)
        securityEnabled = try container.decodeIfPresent(.securityEnabled)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)

        try container.encodeIfPresent(displayName, forKey: .displayName)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(securityEnabled, forKey: .securityEnabled)
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? IntuneGroup else { return false }
      guard self.displayName == object.displayName else { return false }
      guard self.id == object.id else { return false }
      guard self.securityEnabled == object.securityEnabled else { return false }
      return true
    }

    public static func == (lhs: IntuneGroup, rhs: IntuneGroup) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
