//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

/** A collection of  named numeric values grouped by app */
public typealias MetricsValuesByApp = [String: [String: Double]]
