//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

/** an MSA user's hex CID */
public class MSAUser: APIModel {

    /** the user's CID */
    public var hexcid: String

    public init(hexcid: String) {
        self.hexcid = hexcid
    }

    private enum CodingKeys: String, CodingKey {
        case hexcid
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        hexcid = try container.decode(.hexcid)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)

        try container.encode(hexcid, forKey: .hexcid)
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? MSAUser else { return false }
      guard self.hexcid == object.hexcid else { return false }
      return true
    }

    public static func == (lhs: MSAUser, rhs: MSAUser) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
