//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

/** Notification per Account IDs */
public class NotificationTargetAccountIds: APIModel {

    /** List of account IDs to target */
    public var accountIds: [String]

    public init(accountIds: [String]) {
        self.accountIds = accountIds
    }

    private enum CodingKeys: String, CodingKey {
        case accountIds = "account_ids"
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        accountIds = try container.decodeArray(.accountIds)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)

        try container.encode(accountIds, forKey: .accountIds)
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? NotificationTargetAccountIds else { return false }
      guard self.accountIds == object.accountIds else { return false }
      return true
    }

    public static func == (lhs: NotificationTargetAccountIds, rhs: NotificationTargetAccountIds) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
