//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class OS: APIModel {

    /** Count current of OS. */
    public var count: Int?

    /** OS name. */
    public var osName: String?

    /** Count of previous OS. */
    public var previousCount: Int?

    public init(count: Int? = nil, osName: String? = nil, previousCount: Int? = nil) {
        self.count = count
        self.osName = osName
        self.previousCount = previousCount
    }

    private enum CodingKeys: String, CodingKey {
        case count
        case osName = "os_name"
        case previousCount = "previous_count"
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        count = try container.decodeIfPresent(.count)
        osName = try container.decodeIfPresent(.osName)
        previousCount = try container.decodeIfPresent(.previousCount)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)

        try container.encodeIfPresent(count, forKey: .count)
        try container.encodeIfPresent(osName, forKey: .osName)
        try container.encodeIfPresent(previousCount, forKey: .previousCount)
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? OS else { return false }
      guard self.count == object.count else { return false }
      guard self.osName == object.osName else { return false }
      guard self.previousCount == object.previousCount else { return false }
      return true
    }

    public static func == (lhs: OS, rhs: OS) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
