//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

/** The information about the app's owner */
public class Owner: APIModel {

    /** The owner type. Can either be 'org' or 'user' */
    public enum `Type`: String, Codable {
        case org = "org"
        case user = "user"

        public static let cases: [`Type`] = [
          .org,
          .user,
        ]
    }

    /** The unique id (UUID) of the owner */
    public var id: ID

    /** The owner's display name */
    public var displayName: String

    /** The unique name that used to identify the owner */
    public var name: String

    /** The owner type. Can either be 'org' or 'user' */
    public var type: `Type`

    /** The avatar URL of the owner */
    public var avatarURL: String?

    /** The owner's email address */
    public var email: String?

    public init(id: ID, displayName: String, name: String, type: `Type`, avatarURL: String? = nil, email: String? = nil) {
        self.id = id
        self.displayName = displayName
        self.name = name
        self.type = type
        self.avatarURL = avatarURL
        self.email = email
    }

    private enum CodingKeys: String, CodingKey {
        case id
        case displayName = "display_name"
        case name
        case type
        case avatarURL = "avatar_url"
        case email
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        id = try container.decode(.id)
        displayName = try container.decode(.displayName)
        name = try container.decode(.name)
        type = try container.decode(.type)
        avatarURL = try container.decodeIfPresent(.avatarURL)
        email = try container.decodeIfPresent(.email)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)

        try container.encode(id, forKey: .id)
        try container.encode(displayName, forKey: .displayName)
        try container.encode(name, forKey: .name)
        try container.encode(type, forKey: .type)
        try container.encodeIfPresent(avatarURL, forKey: .avatarURL)
        try container.encodeIfPresent(email, forKey: .email)
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? Owner else { return false }
      guard self.id == object.id else { return false }
      guard self.displayName == object.displayName else { return false }
      guard self.name == object.name else { return false }
      guard self.type == object.type else { return false }
      guard self.avatarURL == object.avatarURL else { return false }
      guard self.email == object.email else { return false }
      return true
    }

    public static func == (lhs: Owner, rhs: Owner) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
