//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

/** Set the download URL of an external build */
public class PostExternalDownloadUrl: APIModel {

    /** The new download URL */
    public var downloadURL: String?

    public init(downloadURL: String? = nil) {
        self.downloadURL = downloadURL
    }

    private enum CodingKeys: String, CodingKey {
        case downloadURL = "download_url"
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        downloadURL = try container.decodeIfPresent(.downloadURL)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)

        try container.encodeIfPresent(downloadURL, forKey: .downloadURL)
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? PostExternalDownloadUrl else { return false }
      guard self.downloadURL == object.downloadURL else { return false }
      return true
    }

    public static func == (lhs: PostExternalDownloadUrl, rhs: PostExternalDownloadUrl) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
