//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

/** Response for provisioning a release */
public class ReleaseProvisionResponse: APIModel {

    /** The url to check provisioning status. */
    public var statusURL: String?

    public init(statusURL: String? = nil) {
        self.statusURL = statusURL
    }

    private enum CodingKeys: String, CodingKey {
        case statusURL = "status_url"
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        statusURL = try container.decodeIfPresent(.statusURL)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)

        try container.encodeIfPresent(statusURL, forKey: .statusURL)
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? ReleaseProvisionResponse else { return false }
      guard self.statusURL == object.statusURL else { return false }
      return true
    }

    public static func == (lhs: ReleaseProvisionResponse, rhs: ReleaseProvisionResponse) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
