//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class RepoConfigCommon: APIModel {

    /** The external user id from the repository provider. Required for GitLab.com repositories */
    public var externalUserId: String?

    /** The repository id from the repository provider. Required for repositories connected from GitHub App and GitLab.com */
    public var repoId: String?

    /** The repository's git url, must be a HTTPS URL */
    public var repoURL: String?

    /** The id of the service connection (private). Required for GitLab self-hosted repositories */
    public var serviceConnectionId: String?

    public init(externalUserId: String? = nil, repoId: String? = nil, repoURL: String? = nil, serviceConnectionId: String? = nil) {
        self.externalUserId = externalUserId
        self.repoId = repoId
        self.repoURL = repoURL
        self.serviceConnectionId = serviceConnectionId
    }

    private enum CodingKeys: String, CodingKey {
        case externalUserId = "external_user_id"
        case repoId = "repo_id"
        case repoURL = "repo_url"
        case serviceConnectionId = "service_connection_id"
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        externalUserId = try container.decodeIfPresent(.externalUserId)
        repoId = try container.decodeIfPresent(.repoId)
        repoURL = try container.decodeIfPresent(.repoURL)
        serviceConnectionId = try container.decodeIfPresent(.serviceConnectionId)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)

        try container.encodeIfPresent(externalUserId, forKey: .externalUserId)
        try container.encodeIfPresent(repoId, forKey: .repoId)
        try container.encodeIfPresent(repoURL, forKey: .repoURL)
        try container.encodeIfPresent(serviceConnectionId, forKey: .serviceConnectionId)
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? RepoConfigCommon else { return false }
      guard self.externalUserId == object.externalUserId else { return false }
      guard self.repoId == object.repoId else { return false }
      guard self.repoURL == object.repoURL else { return false }
      guard self.serviceConnectionId == object.serviceConnectionId else { return false }
      return true
    }

    public static func == (lhs: RepoConfigCommon, rhs: RepoConfigCommon) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
