//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class SigningConfig: APIModel {

    /** Indicates if storeFile is specified in the signing configuration */
    public var hasStoreFile: Bool?

    public init(hasStoreFile: Bool? = nil) {
        self.hasStoreFile = hasStoreFile
    }

    private enum CodingKeys: String, CodingKey {
        case hasStoreFile
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        hasStoreFile = try container.decodeIfPresent(.hasStoreFile)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)

        try container.encodeIfPresent(hasStoreFile, forKey: .hasStoreFile)
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? SigningConfig else { return false }
      guard self.hasStoreFile == object.hasStoreFile else { return false }
      return true
    }

    public static func == (lhs: SigningConfig, rhs: SigningConfig) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
