//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

/** Wheither or not to skip the validation for this release */
public class SkipValidationRequest: APIModel {

    /** true if we want to skip the validation, false otherwise */
    public var skipValidation: Bool?

    public init(skipValidation: Bool? = nil) {
        self.skipValidation = skipValidation
    }

    private enum CodingKeys: String, CodingKey {
        case skipValidation = "skip_validation"
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        skipValidation = try container.decodeIfPresent(.skipValidation)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)

        try container.encodeIfPresent(skipValidation, forKey: .skipValidation)
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? SkipValidationRequest else { return false }
      guard self.skipValidation == object.skipValidation else { return false }
      return true
    }

    public static func == (lhs: SkipValidationRequest, rhs: SkipValidationRequest) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
