//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class TestCloudToolset: APIModel {

    /** The TestCloud projects detected */
    public var projects: [Projects]

    public init(projects: [Projects]) {
        self.projects = projects
    }

    private enum CodingKeys: String, CodingKey {
        case projects
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        projects = try container.decodeArray(.projects)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)

        try container.encode(projects, forKey: .projects)
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? TestCloudToolset else { return false }
      guard self.projects == object.projects else { return false }
      return true
    }

    public static func == (lhs: TestCloudToolset, rhs: TestCloudToolset) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
