//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

/** Information required to publish devices to the Apple Developer account and resign the application. */
public class UpdateDevicesRequest: APIModel {

    /** The service_connection_id of the stored Apple credentials instead of username, password. */
    public var accountServiceConnectionId: String?

    /** Array of distribution groups that the devices should be provisioned from. */
    public var destinations: [Destinations]?

    /** Array of device UDID's to be published to the Apple Developer account. */
    public var devices: [String]?

    /** The certificate to use for resigning the application with the updated provisioning profiles. */
    public var p12Base64: String?

    /** The password certificate if one is needed. */
    public var p12Password: String?

    /** The service_connection_id of the stored Apple certificate instead of p12_base64 value. */
    public var p12ServiceConnectionId: String?

    /** The password for the Apple Developer account to publish the devices to. */
    public var password: String?

    /** When set to true, all unprovisioned devices will be published to the Apple Developer account.  When false, only the provided devices will be published to the Apple Developer account. */
    public var publishAllDevices: Bool?

    /** When provided, will update the provided release with the new set of devices. By default the latest release of the distribution group is used when this property is omitted. If `release_id` is passed in the path, there is no need to pass in the body as well. */
    public var releaseId: Double?

    /** The username for the Apple Developer account to publish the devices to. */
    public var username: String?

    public init(accountServiceConnectionId: String? = nil, destinations: [Destinations]? = nil, devices: [String]? = nil, p12Base64: String? = nil, p12Password: String? = nil, p12ServiceConnectionId: String? = nil, password: String? = nil, publishAllDevices: Bool? = nil, releaseId: Double? = nil, username: String? = nil) {
        self.accountServiceConnectionId = accountServiceConnectionId
        self.destinations = destinations
        self.devices = devices
        self.p12Base64 = p12Base64
        self.p12Password = p12Password
        self.p12ServiceConnectionId = p12ServiceConnectionId
        self.password = password
        self.publishAllDevices = publishAllDevices
        self.releaseId = releaseId
        self.username = username
    }

    private enum CodingKeys: String, CodingKey {
        case accountServiceConnectionId = "account_service_connection_id"
        case destinations
        case devices
        case p12Base64 = "p12_base64"
        case p12Password = "p12_password"
        case p12ServiceConnectionId = "p12_service_connection_id"
        case password
        case publishAllDevices = "publish_all_devices"
        case releaseId = "release_id"
        case username
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        accountServiceConnectionId = try container.decodeIfPresent(.accountServiceConnectionId)
        destinations = try container.decodeArrayIfPresent(.destinations)
        devices = try container.decodeArrayIfPresent(.devices)
        p12Base64 = try container.decodeIfPresent(.p12Base64)
        p12Password = try container.decodeIfPresent(.p12Password)
        p12ServiceConnectionId = try container.decodeIfPresent(.p12ServiceConnectionId)
        password = try container.decodeIfPresent(.password)
        publishAllDevices = try container.decodeIfPresent(.publishAllDevices)
        releaseId = try container.decodeIfPresent(.releaseId)
        username = try container.decodeIfPresent(.username)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)

        try container.encodeIfPresent(accountServiceConnectionId, forKey: .accountServiceConnectionId)
        try container.encodeIfPresent(destinations, forKey: .destinations)
        try container.encodeIfPresent(devices, forKey: .devices)
        try container.encodeIfPresent(p12Base64, forKey: .p12Base64)
        try container.encodeIfPresent(p12Password, forKey: .p12Password)
        try container.encodeIfPresent(p12ServiceConnectionId, forKey: .p12ServiceConnectionId)
        try container.encodeIfPresent(password, forKey: .password)
        try container.encodeIfPresent(publishAllDevices, forKey: .publishAllDevices)
        try container.encodeIfPresent(releaseId, forKey: .releaseId)
        try container.encodeIfPresent(username, forKey: .username)
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? UpdateDevicesRequest else { return false }
      guard self.accountServiceConnectionId == object.accountServiceConnectionId else { return false }
      guard self.destinations == object.destinations else { return false }
      guard self.devices == object.devices else { return false }
      guard self.p12Base64 == object.p12Base64 else { return false }
      guard self.p12Password == object.p12Password else { return false }
      guard self.p12ServiceConnectionId == object.p12ServiceConnectionId else { return false }
      guard self.password == object.password else { return false }
      guard self.publishAllDevices == object.publishAllDevices else { return false }
      guard self.releaseId == object.releaseId else { return false }
      guard self.username == object.username else { return false }
      return true
    }

    public static func == (lhs: UpdateDevicesRequest, rhs: UpdateDevicesRequest) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
