//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class UserNameUpdateRequest: APIModel {

    /** The new, unique name that is used to identify. */
    public var name: String?

    public init(name: String? = nil) {
        self.name = name
    }

    private enum CodingKeys: String, CodingKey {
        case name
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        name = try container.decodeIfPresent(.name)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)

        try container.encodeIfPresent(name, forKey: .name)
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? UserNameUpdateRequest else { return false }
      guard self.name == object.name else { return false }
      return true
    }

    public static func == (lhs: UserNameUpdateRequest, rhs: UserNameUpdateRequest) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
