//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

extension EngagementAPI.Codepush {

    /**
    Check for updates
    */
    public enum LegacyCodePushAcquisitionUpdateCheck {

        public static let service = APIService<Response>(id: "legacyCodePushAcquisition_updateCheck", tag: "codepush", method: "GET", path: "/v0.1/legacy/updateCheck", hasBody: false, securityRequirement: SecurityRequirement(type: "APIToken", scope: ""))

        public final class Request: APIRequest<Response> {

            public struct Options {

                public var deploymentKey: String?

                public var appVersion: String?

                public var packageHash: String?

                public var label: String?

                public var clientUniqueId: String?

                public var isCompanion: String?

                public init(deploymentKey: String? = nil, appVersion: String? = nil, packageHash: String? = nil, label: String? = nil, clientUniqueId: String? = nil, isCompanion: String? = nil) {
                    self.deploymentKey = deploymentKey
                    self.appVersion = appVersion
                    self.packageHash = packageHash
                    self.label = label
                    self.clientUniqueId = clientUniqueId
                    self.isCompanion = isCompanion
                }
            }

            public var options: Options

            public init(options: Options) {
                self.options = options
                super.init(service: LegacyCodePushAcquisitionUpdateCheck.service)
            }

            /// convenience initialiser so an Option doesn't have to be created
            public convenience init(deploymentKey: String? = nil, appVersion: String? = nil, packageHash: String? = nil, label: String? = nil, clientUniqueId: String? = nil, isCompanion: String? = nil) {
                let options = Options(deploymentKey: deploymentKey, appVersion: appVersion, packageHash: packageHash, label: label, clientUniqueId: clientUniqueId, isCompanion: isCompanion)
                self.init(options: options)
            }

            public override var parameters: [String: Any] {
                var params: [String: Any] = [:]
                if let deploymentKey = options.deploymentKey {
                  params["deploymentKey"] = deploymentKey
                }
                if let appVersion = options.appVersion {
                  params["appVersion"] = appVersion
                }
                if let packageHash = options.packageHash {
                  params["packageHash"] = packageHash
                }
                if let label = options.label {
                  params["label"] = label
                }
                if let clientUniqueId = options.clientUniqueId {
                  params["clientUniqueId"] = clientUniqueId
                }
                if let isCompanion = options.isCompanion {
                  params["isCompanion"] = isCompanion
                }
                return params
            }
        }

        public enum Response: APIResponseValue, CustomStringConvertible, CustomDebugStringConvertible {

            /** Check for updates */
            public class Status200: APIModel {

                public var updateInfo: UNKNOWN_ALL_OFF

                public init(updateInfo: UNKNOWN_ALL_OFF) {
                    self.updateInfo = updateInfo
                }

                private enum CodingKeys: String, CodingKey {
                    case updateInfo
                }

                public required init(from decoder: Decoder) throws {
                    let container = try decoder.container(keyedBy: CodingKeys.self)

                    updateInfo = try container.decode(.updateInfo)
                }

                public func encode(to encoder: Encoder) throws {
                    var container = encoder.container(keyedBy: CodingKeys.self)

                    try container.encode(updateInfo, forKey: .updateInfo)
                }

                public func isEqual(to object: Any?) -> Bool {
                  guard let object = object as? Status200 else { return false }
                  guard self.updateInfo == object.updateInfo else { return false }
                  return true
                }

                public static func == (lhs: Status200, rhs: Status200) -> Bool {
                    return lhs.isEqual(to: rhs)
                }
            }

            /** Check for updates */
            public class DefaultResponse: APIModel {

                public var message: String

                public init(message: String) {
                    self.message = message
                }

                private enum CodingKeys: String, CodingKey {
                    case message
                }

                public required init(from decoder: Decoder) throws {
                    let container = try decoder.container(keyedBy: CodingKeys.self)

                    message = try container.decode(.message)
                }

                public func encode(to encoder: Encoder) throws {
                    var container = encoder.container(keyedBy: CodingKeys.self)

                    try container.encode(message, forKey: .message)
                }

                public func isEqual(to object: Any?) -> Bool {
                  guard let object = object as? DefaultResponse else { return false }
                  guard self.message == object.message else { return false }
                  return true
                }

                public static func == (lhs: DefaultResponse, rhs: DefaultResponse) -> Bool {
                    return lhs.isEqual(to: rhs)
                }
            }
            public typealias SuccessType = Status200

            /** Success */
            case status200(Status200)

            /** Error */
            case defaultResponse(statusCode: Int, DefaultResponse)

            public var success: Status200? {
                switch self {
                case .status200(let response): return response
                default: return nil
                }
            }

            public var failure: DefaultResponse? {
                switch self {
                case .defaultResponse(_, let response): return response
                default: return nil
                }
            }

            /// either success or failure value. Success is anything in the 200..<300 status code range
            public var responseResult: APIResponseResult<Status200, DefaultResponse> {
                if let successValue = success {
                    return .success(successValue)
                } else if let failureValue = failure {
                    return .failure(failureValue)
                } else {
                    fatalError("Response does not have success or failure response")
                }
            }

            public var response: Any {
                switch self {
                case .status200(let response): return response
                case .defaultResponse(_, let response): return response
                }
            }

            public var statusCode: Int {
                switch self {
                case .status200: return 200
                case .defaultResponse(let statusCode, _): return statusCode
                }
            }

            public var successful: Bool {
                switch self {
                case .status200: return true
                case .defaultResponse: return false
                }
            }

            public init(statusCode: Int, data: Data, decoder: ResponseDecoder) throws {
                switch statusCode {
                case 200: self = try .status200(decoder.decode(Status200.self, from: data))
                default: self = try .defaultResponse(statusCode: statusCode, decoder.decode(DefaultResponse.self, from: data))
                }
            }

            public var description: String {
                return "\(statusCode) \(successful ? "success" : "failure")"
            }

            public var debugDescription: String {
                var string = description
                let responseString = "\(response)"
                if responseString != "()" {
                    string += "\n\(responseString)"
                }
                return string
            }
        }
    }
}
