//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

extension EngagementAPI.Test {

    /**
    Get information about the currently active subscriptions, if any
    */
    public enum TestGetSubscriptions {

        public static let service = APIService<Response>(id: "test_getSubscriptions", tag: "test", method: "GET", path: "/v0.1/apps/{owner_name}/{app_name}/subscriptions", hasBody: false, securityRequirement: SecurityRequirement(type: "APIToken", scope: ""))

        public final class Request: APIRequest<Response> {

            public struct Options {

                /** The name of the owner */
                public var ownerName: String

                /** The name of the application */
                public var appName: String

                public init(ownerName: String, appName: String) {
                    self.ownerName = ownerName
                    self.appName = appName
                }
            }

            public var options: Options

            public init(options: Options) {
                self.options = options
                super.init(service: TestGetSubscriptions.service)
            }

            /// convenience initialiser so an Option doesn't have to be created
            public convenience init(ownerName: String, appName: String) {
                let options = Options(ownerName: ownerName, appName: appName)
                self.init(options: options)
            }

            public override var path: String {
                return super.path.replacingOccurrences(of: "{" + "ownerName" + "}", with: "\(self.options.ownerName)").replacingOccurrences(of: "{" + "appName" + "}", with: "\(self.options.appName)")
            }
        }

        public enum Response: APIResponseValue, CustomStringConvertible, CustomDebugStringConvertible {

            /** Get information about the currently active subscriptions, if any */
            public class Status200: APIModel {

                /** Is the subscription currently active? */
                public var active: Bool?

                /** The number of days left in the subscription */
                public var daysLeft: Double?

                /** The date the subscription will end or ended */
                public var endsAt: String?

                /** Id of the subscription */
                public var id: ID?

                /** The date the subscription began */
                public var startsAt: String?

                public var tier: Tier?

                /** Get information about the currently active subscriptions, if any */
                public class Tier: APIModel {

                    /** The name of the tier */
                    public var name: String?

                    public init(name: String? = nil) {
                        self.name = name
                    }

                    private enum CodingKeys: String, CodingKey {
                        case name
                    }

                    public required init(from decoder: Decoder) throws {
                        let container = try decoder.container(keyedBy: CodingKeys.self)

                        name = try container.decodeIfPresent(.name)
                    }

                    public func encode(to encoder: Encoder) throws {
                        var container = encoder.container(keyedBy: CodingKeys.self)

                        try container.encodeIfPresent(name, forKey: .name)
                    }

                    public func isEqual(to object: Any?) -> Bool {
                      guard let object = object as? Tier else { return false }
                      guard self.name == object.name else { return false }
                      return true
                    }

                    public static func == (lhs: Tier, rhs: Tier) -> Bool {
                        return lhs.isEqual(to: rhs)
                    }
                }

                public init(active: Bool? = nil, daysLeft: Double? = nil, endsAt: String? = nil, id: ID? = nil, startsAt: String? = nil, tier: Tier? = nil) {
                    self.active = active
                    self.daysLeft = daysLeft
                    self.endsAt = endsAt
                    self.id = id
                    self.startsAt = startsAt
                    self.tier = tier
                }

                private enum CodingKeys: String, CodingKey {
                    case active
                    case daysLeft
                    case endsAt
                    case id
                    case startsAt
                    case tier
                }

                public required init(from decoder: Decoder) throws {
                    let container = try decoder.container(keyedBy: CodingKeys.self)

                    active = try container.decodeIfPresent(.active)
                    daysLeft = try container.decodeIfPresent(.daysLeft)
                    endsAt = try container.decodeIfPresent(.endsAt)
                    id = try container.decodeIfPresent(.id)
                    startsAt = try container.decodeIfPresent(.startsAt)
                    tier = try container.decodeIfPresent(.tier)
                }

                public func encode(to encoder: Encoder) throws {
                    var container = encoder.container(keyedBy: CodingKeys.self)

                    try container.encodeIfPresent(active, forKey: .active)
                    try container.encodeIfPresent(daysLeft, forKey: .daysLeft)
                    try container.encodeIfPresent(endsAt, forKey: .endsAt)
                    try container.encodeIfPresent(id, forKey: .id)
                    try container.encodeIfPresent(startsAt, forKey: .startsAt)
                    try container.encodeIfPresent(tier, forKey: .tier)
                }

                public func isEqual(to object: Any?) -> Bool {
                  guard let object = object as? Status200 else { return false }
                  guard self.active == object.active else { return false }
                  guard self.daysLeft == object.daysLeft else { return false }
                  guard self.endsAt == object.endsAt else { return false }
                  guard self.id == object.id else { return false }
                  guard self.startsAt == object.startsAt else { return false }
                  guard self.tier == object.tier else { return false }
                  return true
                }

                public static func == (lhs: Status200, rhs: Status200) -> Bool {
                    return lhs.isEqual(to: rhs)
                }
            }
            public typealias SuccessType = Status200

            /** OK */
            case status200(Status200)

            public var success: Status200? {
                switch self {
                case .status200(let response): return response
                }
            }

            public var response: Any {
                switch self {
                case .status200(let response): return response
                }
            }

            public var statusCode: Int {
                switch self {
                case .status200: return 200
                }
            }

            public var successful: Bool {
                switch self {
                case .status200: return true
                }
            }

            public init(statusCode: Int, data: Data, decoder: ResponseDecoder) throws {
                switch statusCode {
                case 200: self = try .status200(decoder.decode(Status200.self, from: data))
                default: throw APIClientError.unexpectedStatusCode(statusCode: statusCode, data: data)
                }
            }

            public var description: String {
                return "\(statusCode) \(successful ? "success" : "failure")"
            }

            public var debugDescription: String {
                var string = description
                let responseString = "\(response)"
                if responseString != "()" {
                    string += "\n\(responseString)"
                }
                return string
            }
        }
    }
}
