//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

extension EngagementAPI.Errors {

    /**
    List of error groups
    */
    public enum ErrorsGroupList {

        public static let service = APIService<Response>(id: "Errors_GroupList", tag: "errors", method: "GET", path: "/v0.1/apps/{owner_name}/{app_name}/errors/errorGroups", hasBody: false, securityRequirement: SecurityRequirement(type: "APIToken", scope: ""))

        public final class Request: APIRequest<Response> {

            public struct Options {

                public var version: String?

                /** app build */
                public var appBuild: String?

                public var groupState: String?

                /** Start date time in data in ISO 8601 date time format */
                public var start: DateTime

                /** Last date time in data in ISO 8601 date time format */
                public var end: DateTime?

                /** controls the sorting order and sorting based on which column */
                public var dollarorderby: String?

                /** The maximum number of results to return. (0 will fetch all results till the max number.) */
                public var dollartop: Int?

                /** Type of error (handled vs unhandled), including All */
                public var errorType: ErrorTypeParameter?

                /** The name of the owner */
                public var ownerName: String

                /** The name of the application */
                public var appName: String

                public init(version: String? = nil, appBuild: String? = nil, groupState: String? = nil, start: DateTime, end: DateTime? = nil, dollarorderby: String? = nil, dollartop: Int? = nil, errorType: ErrorTypeParameter? = nil, ownerName: String, appName: String) {
                    self.version = version
                    self.appBuild = appBuild
                    self.groupState = groupState
                    self.start = start
                    self.end = end
                    self.dollarorderby = dollarorderby
                    self.dollartop = dollartop
                    self.errorType = errorType
                    self.ownerName = ownerName
                    self.appName = appName
                }
            }

            public var options: Options

            public init(options: Options) {
                self.options = options
                super.init(service: ErrorsGroupList.service)
            }

            /// convenience initialiser so an Option doesn't have to be created
            public convenience init(version: String? = nil, appBuild: String? = nil, groupState: String? = nil, start: DateTime, end: DateTime? = nil, dollarorderby: String? = nil, dollartop: Int? = nil, errorType: ErrorTypeParameter? = nil, ownerName: String, appName: String) {
                let options = Options(version: version, appBuild: appBuild, groupState: groupState, start: start, end: end, dollarorderby: dollarorderby, dollartop: dollartop, errorType: errorType, ownerName: ownerName, appName: appName)
                self.init(options: options)
            }

            public override var path: String {
                return super.path.replacingOccurrences(of: "{" + "ownerName" + "}", with: "\(self.options.ownerName)").replacingOccurrences(of: "{" + "appName" + "}", with: "\(self.options.appName)")
            }

            public override var parameters: [String: Any] {
                var params: [String: Any] = [:]
                if let version = options.version {
                  params["version"] = version
                }
                if let appBuild = options.appBuild {
                  params["app_build"] = appBuild
                }
                if let groupState = options.groupState {
                  params["groupState"] = groupState
                }
                params["start"] = options.start.encode()
                if let end = options.end?.encode() {
                  params["end"] = end
                }
                if let dollarorderby = options.dollarorderby {
                  params["$orderby"] = dollarorderby
                }
                if let dollartop = options.dollartop {
                  params["$top"] = dollartop
                }
                if let errorType = options.errorType?.encode() {
                  params["errorType"] = errorType
                }
                return params
            }
        }

        public enum Response: APIResponseValue, CustomStringConvertible, CustomDebugStringConvertible {

            /** List of error groups */
            public class Status200: APIModel {

                public var errorGroups: [[String: Any]]?

                public var nextLink: String?

                public init(errorGroups: [[String: Any]]? = nil, nextLink: String? = nil) {
                    self.errorGroups = errorGroups
                    self.nextLink = nextLink
                }

                private enum CodingKeys: String, CodingKey {
                    case errorGroups
                    case nextLink
                }

                public required init(from decoder: Decoder) throws {
                    let container = try decoder.container(keyedBy: CodingKeys.self)

                    errorGroups = try container.decodeAnyIfPresent(.errorGroups)
                    nextLink = try container.decodeIfPresent(.nextLink)
                }

                public func encode(to encoder: Encoder) throws {
                    var container = encoder.container(keyedBy: CodingKeys.self)

                    try container.encodeAnyIfPresent(errorGroups, forKey: .errorGroups)
                    try container.encodeIfPresent(nextLink, forKey: .nextLink)
                }

                public func isEqual(to object: Any?) -> Bool {
                  guard let object = object as? Status200 else { return false }
                  guard self.errorGroups == object.errorGroups else { return false }
                  guard self.nextLink == object.nextLink else { return false }
                  return true
                }

                public static func == (lhs: Status200, rhs: Status200) -> Bool {
                    return lhs.isEqual(to: rhs)
                }
            }

            /** List of error groups */
            public class DefaultResponse: APIModel {

                public var error: ErrorType

                /** List of error groups */
                public class ErrorType: APIModel {

                    /** List of error groups */
                    public enum Code: String, Codable {
                        case badRequest = "BadRequest"
                        case conflict = "Conflict"
                        case notAcceptable = "NotAcceptable"
                        case notFound = "NotFound"
                        case internalServerError = "InternalServerError"
                        case unauthorized = "Unauthorized"
                        case tooManyRequests = "TooManyRequests"

                        public static let cases: [Code] = [
                          .badRequest,
                          .conflict,
                          .notAcceptable,
                          .notFound,
                          .internalServerError,
                          .unauthorized,
                          .tooManyRequests,
                        ]
                    }

                    public var code: Code

                    public var message: String

                    public init(code: Code, message: String) {
                        self.code = code
                        self.message = message
                    }

                    private enum CodingKeys: String, CodingKey {
                        case code
                        case message
                    }

                    public required init(from decoder: Decoder) throws {
                        let container = try decoder.container(keyedBy: CodingKeys.self)

                        code = try container.decode(.code)
                        message = try container.decode(.message)
                    }

                    public func encode(to encoder: Encoder) throws {
                        var container = encoder.container(keyedBy: CodingKeys.self)

                        try container.encode(code, forKey: .code)
                        try container.encode(message, forKey: .message)
                    }

                    public func isEqual(to object: Any?) -> Bool {
                      guard let object = object as? ErrorType else { return false }
                      guard self.code == object.code else { return false }
                      guard self.message == object.message else { return false }
                      return true
                    }

                    public static func == (lhs: ErrorType, rhs: ErrorType) -> Bool {
                        return lhs.isEqual(to: rhs)
                    }
                }

                public init(error: ErrorType) {
                    self.error = error
                }

                private enum CodingKeys: String, CodingKey {
                    case error
                }

                public required init(from decoder: Decoder) throws {
                    let container = try decoder.container(keyedBy: CodingKeys.self)

                    error = try container.decode(.error)
                }

                public func encode(to encoder: Encoder) throws {
                    var container = encoder.container(keyedBy: CodingKeys.self)

                    try container.encode(error, forKey: .error)
                }

                public func isEqual(to object: Any?) -> Bool {
                  guard let object = object as? DefaultResponse else { return false }
                  guard self.error == object.error else { return false }
                  return true
                }

                public static func == (lhs: DefaultResponse, rhs: DefaultResponse) -> Bool {
                    return lhs.isEqual(to: rhs)
                }
            }
            public typealias SuccessType = Status200

            /** List of error groups */
            case status200(Status200)

            /** Error code with reason */
            case defaultResponse(statusCode: Int, DefaultResponse)

            public var success: Status200? {
                switch self {
                case .status200(let response): return response
                default: return nil
                }
            }

            public var failure: DefaultResponse? {
                switch self {
                case .defaultResponse(_, let response): return response
                default: return nil
                }
            }

            /// either success or failure value. Success is anything in the 200..<300 status code range
            public var responseResult: APIResponseResult<Status200, DefaultResponse> {
                if let successValue = success {
                    return .success(successValue)
                } else if let failureValue = failure {
                    return .failure(failureValue)
                } else {
                    fatalError("Response does not have success or failure response")
                }
            }

            public var response: Any {
                switch self {
                case .status200(let response): return response
                case .defaultResponse(_, let response): return response
                }
            }

            public var statusCode: Int {
                switch self {
                case .status200: return 200
                case .defaultResponse(let statusCode, _): return statusCode
                }
            }

            public var successful: Bool {
                switch self {
                case .status200: return true
                case .defaultResponse: return false
                }
            }

            public init(statusCode: Int, data: Data, decoder: ResponseDecoder) throws {
                switch statusCode {
                case 200: self = try .status200(decoder.decode(Status200.self, from: data))
                default: self = try .defaultResponse(statusCode: statusCode, decoder.decode(DefaultResponse.self, from: data))
                }
            }

            public var description: String {
                return "\(statusCode) \(successful ? "success" : "failure")"
            }

            public var debugDescription: String {
                var string = description
                let responseString = "\(response)"
                if responseString != "()" {
                    string += "\n\(responseString)"
                }
                return string
            }
        }
    }
}
