//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

public enum ErrorType: String, Codable {
    case crashingErrors = "CrashingErrors"
    case handledErrors = "HandledErrors"

    public static let cases: [ErrorType] = [
      .crashingErrors,
      .handledErrors,
    ]
}
