//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

/** Type of error (handled vs unhandled), including All */
public enum ErrorTypeParameter: String, Codable {
    case all = "all"
    case unhandledError = "unhandledError"
    case handledError = "handledError"

    public static let cases: [ErrorTypeParameter] = [
      .all,
      .unhandledError,
      .handledError,
    ]
}
