//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

public enum GroupStatus: String, Codable {
    case `open` = "open"
    case closed = "closed"
    case ignored = "ignored"

    public static let cases: [GroupStatus] = [
      .`open`,
      .closed,
      .ignored,
    ]
}
