//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

/** Type of the queue. */
public enum QueueTypeParameter: String, Codable {
    case analytics = "analytics"
    case handledErrorParser = "handledErrorParser"
    case handledErrorAggregation = "handledErrorAggregation"

    public static let cases: [QueueTypeParameter] = [
      .analytics,
      .handledErrorParser,
      .handledErrorAggregation,
    ]
}
